services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/Dockerfile.next
    restart: always
    ports:
      - 3000:3000
    develop:
      watch:
        - path: .
          target: /src
          action: sync
        - path: .
          target: package.json
          action: rebuild
          
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/Dockerfile.nest
      args:
        SERVICE_URI: api
        SERVICE_NAME: api
    restart: always
    ports:
      - 3001:3001
    develop:
      watch:
        - path: .
          target: /src
          action: sync
        - path: .
          target: package.json
          action: rebuild