services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/Dockerfile.next
    restart: always
    ports:
      - 3000:3000
    develop:
      watch:
        - path: .
          target: /src
          action: sync
        - path: .
          target: package.json
          action: rebuild
          
  api:
    depends_on:
      - nats
    container_name: api
    build:
      context: .
      dockerfile: apps/Dockerfile.nest
      args:
        SERVICE_URI: api
        SERVICE_NAME: api
    restart: always
    ports:
      - 3001:3001
    develop:
      watch:
        - path: .
          target: /src
          action: sync
        - path: .
          target: package.json
          action: rebuild
      
  redis-service:
    depends_on:
      - nats
    container_name: redis-service
    build:
      context: .
      dockerfile: apps/Dockerfile.nest
      args:
        SERVICE_NAME: redis-service
        SERVICE_URI: services/redis-service
    restart: always 
    develop:
      watch:
      - path: /redis-service
        target: /src
        action: sync
      - path: /redis-service
        target: package.json
        action: rebuild
  
  data-service:
    depends_on:
      - nats
    container_name: data-service
    build:
      context: .
      dockerfile: apps/Dockerfile.nest
      args:
        SERVICE_URI: services/data-service
        SERVICE_NAME: data-service
    restart: always
    develop:
      watch:
      - path: /data-service
        target: /src
        action: sync
      - path: /data-service
        target: package.json
        action: rebuild

  nats:
    container_name: nats
    image: nats:latest
    restart: always
    ports:
      - 4222:4222
      - 8222:8222