ARG NODE_VERSION=24.13.1
ARG SERVICE_NAME
ARG SERVICE_URI
FROM node:${NODE_VERSION}-slim AS base

RUN corepack enable && corepack prepare pnpm@8.15.5 --activate

# The web Dockerfile is copy-pasted into our main docs at /docs/handbook/deploying-with-docker.
# Make sure you update this Dockerfile, the Dockerfile in the web workspace and copy that over to Dockerfile in the docs.
WORKDIR /app

FROM base AS prepare
ARG SERVICE_NAME
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
# Set working directory
RUN yarn global add turbo
COPY . .
RUN turbo prune ${SERVICE_NAME} --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS builder

# First install dependencies (as they change less often)
COPY --from=prepare /app/out/json/ .
RUN pnpm install --frozen-lockfile --node-linker=hoisted

# Build the project and its dependencies
COPY --from=prepare /app/out/full/ .

# Uncomment and use build args to enable remote caching
# ARG TURBO_TEAM
# ENV TURBO_TEAM=$TURBO_TEAM

# ARG TURBO_TOKEN
# ENV TURBO_TOKEN=$TURBO_TOKEN

RUN pnpm turbo build

FROM node:${NODE_VERSION}-alpine AS runner
ARG SERVICE_NAME
ARG SERVICE_URI
ENV SERVICE_URI=${SERVICE_URI}
WORKDIR /app
# Don't run production as root
RUN addgroup -S -g 1001 nestjs
RUN adduser -S -D -u 1001 -G nestjs ${SERVICE_NAME}
USER ${SERVICE_NAME}
COPY --from=builder /app .

CMD node apps/${SERVICE_URI}/dist/main.js